import numpy as np
import os
import matplotlib.pyplot as plt
from MyFunctions.DicomImage import DicomImage #Custom Class
import MyFunctions.pickle_functions as PF
import MyFunctions.Extract_Images_r as Extract_r
import time
###
import numpy as np
import time
import matplotlib.pyplot as plt

os.system("clear")
initial = time.time()
path ='/Volumes/Cle_Python/Python'

#Fan1 = PF.pickle_open(os.path.dirname(os.path.realpath(__file__))+'/Fantome_1_1min_Canny.pkl')
Fan1 = PF.pickle_open(path+'/Fantome_1_1min_Canny.pkl')
Fan5 = PF.pickle_open(path+'/Fantome_5_1min_Canny.pkl')
Fan6 = PF.pickle_open(path+'/Fantome_6_1min_Canny.pkl')
Fan7 = PF.pickle_open(path+'/Fantome_7_1min_Canny.pkl')
Fan8 = PF.pickle_open(path+'/Fantome_8_1min_Canny.pkl')
print(len(Fan1.voi_statistics))
for i in range(int(len(Fan1.voi_statistics)/3)):
    plt.figure(1)
    plt.plot(Fan1.time,Fan1.voi_statistics[i*3],label=f"{i}")
    plt.xlabel('Time');plt.ylabel('Activity');plt.title(f"Vial {Fan1.name}\n{Fan1.Description}");plt.grid();plt.legend()
    plt.figure(2)
    plt.plot(Fan1.time,Fan1.voi_statistics[i*3+1],label=f"{i}")
    plt.xlabel('Time');plt.ylabel('Activity');plt.title(f"Comp1 {Fan1.name}\n{Fan1.Description}");plt.grid();plt.legend()
    plt.figure(3)
    plt.plot(Fan1.time,Fan1.voi_statistics[i*3+2],label=f"{i}")
    plt.xlabel('Time');plt.ylabel('Activity');plt.title(f"Comp2 {Fan1.name}\n{Fan1.Description}");plt.grid();plt.legend()

    plt.figure(4)
    plt.plot(Fan5.time,Fan5.voi_statistics[i*3],label=f"{i}")
    plt.xlabel('Time');plt.ylabel('Activity');plt.title(f"Vial {Fan5.name}\n{Fan5.Description}");plt.grid();plt.legend()
    plt.figure(5)
    plt.plot(Fan5.time,Fan5.voi_statistics[i*3+1],label=f"{i}")
    plt.xlabel('Time');plt.ylabel('Activity');plt.title(f"Comp1 {Fan5.name}\n{Fan5.Description}");plt.grid();plt.legend()
    plt.figure(6)
    plt.plot(Fan5.time,Fan5.voi_statistics[i*3+2],label=f"{i}")
    plt.xlabel('Time');plt.ylabel('Activity');plt.title(f"Comp2 {Fan5.name}\n{Fan5.Description}");plt.grid();plt.legend()

    plt.figure(7)
    plt.plot(Fan6.time,Fan6.voi_statistics[i*3],label=f"{i}")
    plt.xlabel('Time');plt.ylabel('Activity');plt.title(f"Vial {Fan6.name}\n{Fan6.Description}");plt.grid();plt.legend()
    plt.figure(8)
    plt.plot(Fan6.time,Fan6.voi_statistics[i*3+1],label=f"{i}")
    plt.xlabel('Time');plt.ylabel('Activity');plt.title(f"Comp1 {Fan6.name}\n{Fan6.Description}");plt.grid();plt.legend()
    plt.figure(9)
    plt.plot(Fan6.time,Fan6.voi_statistics[i*3+2],label=f"{i}")
    plt.xlabel('Time');plt.ylabel('Activity');plt.title(f"Comp2 {Fan6.name}\n{Fan6.Description}");plt.grid();plt.legend()

    plt.figure(10)
    plt.plot(Fan7.time,Fan7.voi_statistics[i*3],label=f"{i}")
    plt.xlabel('Time');plt.ylabel('Activity');plt.title(f"Vial {Fan7.name}\n{Fan7.Description}");plt.grid();plt.legend()
    plt.figure(11)
    plt.plot(Fan7.time,Fan7.voi_statistics[i*3+1],label=f"{i}")
    plt.xlabel('Time');plt.ylabel('Activity');plt.title(f"Comp1 {Fan7.name}\n{Fan7.Description}");plt.grid();plt.legend()
    plt.figure(12)
    plt.plot(Fan7.time,Fan7.voi_statistics[i*3+2],label=f"{i}")
    plt.xlabel('Time');plt.ylabel('Activity');plt.title(f"Comp2 {Fan7.name}\n{Fan7.Description}");plt.grid();plt.legend()

    plt.figure(13)
    plt.plot(Fan8.time,Fan8.voi_statistics[i*3],label=f"{i}")
    plt.xlabel('Time');plt.ylabel('Activity');plt.title(f"Vial {Fan8.name}\n{Fan8.Description}");plt.grid();plt.legend()
    plt.figure(14)
    plt.plot(Fan8.time,Fan8.voi_statistics[i*3+1],label=f"{i}")
    plt.xlabel('Time');plt.ylabel('Activity');plt.title(f"Comp1 {Fan8.name}\n{Fan8.Description}");plt.grid();plt.legend()
    plt.figure(15)
    plt.plot(Fan8.time,Fan8.voi_statistics[i*3+2],label=f"{i}")
    plt.xlabel('Time');plt.ylabel('Activity');plt.title(f"Comp2 {Fan8.name}\n{Fan8.Description}");plt.grid();plt.legend()

    plt.figure(22)
    plt.plot(Fan7.voi_voxels[:])

avg_stat_1_vial = np.zeros_like(Fan1.voi_statistics[i*3])
avg_stat_1_comp1 = np.zeros_like(Fan1.voi_statistics[i*3+1])
avg_stat_1_comp2 = np.zeros_like(Fan1.voi_statistics[i*3+2])
avg_stat_5_vial = np.zeros_like(Fan5.voi_statistics[i*3])
avg_stat_5_comp1 = np.zeros_like(Fan5.voi_statistics[i*3+1])
avg_stat_5_comp2 = np.zeros_like(Fan5.voi_statistics[i*3+2])
avg_stat_6_vial = np.zeros_like(Fan6.voi_statistics[i*3])
avg_stat_6_comp1 = np.zeros_like(Fan6.voi_statistics[i*3+1])
avg_stat_6_comp2 = np.zeros_like(Fan6.voi_statistics[i*3+2])
avg_stat_7_vial = np.zeros_like(Fan7.voi_statistics[i*3])
avg_stat_7_comp1 = np.zeros_like(Fan7.voi_statistics[i*3+1])
avg_stat_7_comp2 = np.zeros_like(Fan7.voi_statistics[i*3+2])
avg_stat_8_vial = np.zeros_like(Fan8.voi_statistics[i*3])
avg_stat_8_comp1 = np.zeros_like(Fan8.voi_statistics[i*3+1])
avg_stat_8_comp2 = np.zeros_like(Fan8.voi_statistics[i*3+2])

std_stat_1_vial = np.zeros_like(Fan1.voi_statistics[i*3])
std_stat_1_comp1 = np.zeros_like(Fan1.voi_statistics[i*3+1])
std_stat_1_comp2 = np.zeros_like(Fan1.voi_statistics[i*3+2])
std_stat_5_vial = np.zeros_like(Fan5.voi_statistics[i*3])
std_stat_5_comp1 = np.zeros_like(Fan5.voi_statistics[i*3+1])
std_stat_5_comp2 = np.zeros_like(Fan5.voi_statistics[i*3+2])
std_stat_6_vial = np.zeros_like(Fan6.voi_statistics[i*3])
std_stat_6_comp1 = np.zeros_like(Fan6.voi_statistics[i*3+1])
std_stat_6_comp2 = np.zeros_like(Fan6.voi_statistics[i*3+2])
std_stat_7_vial = np.zeros_like(Fan7.voi_statistics[i*3])
std_stat_7_comp1 = np.zeros_like(Fan7.voi_statistics[i*3+1])
std_stat_7_comp2 = np.zeros_like(Fan7.voi_statistics[i*3+2])
std_stat_8_vial = np.zeros_like(Fan8.voi_statistics[i*3])
std_stat_8_comp1 = np.zeros_like(Fan8.voi_statistics[i*3+1])
std_stat_8_comp2 = np.zeros_like(Fan8.voi_statistics[i*3+2])
for i in range(int(len(Fan1.voi_statistics)/3)):
    avg_stat_1_vial += Fan1.voi_statistics[i*3]/(len(Fan1.voi_statistics)/3)
    avg_stat_1_comp1 += Fan1.voi_statistics[i*3+1]/(len(Fan1.voi_statistics)/3)
    avg_stat_1_comp2 += Fan1.voi_statistics[i*3+2]/(len(Fan1.voi_statistics)/3)
    avg_stat_5_vial += Fan5.voi_statistics[i*3]/(len(Fan5.voi_statistics)/3)
    avg_stat_5_comp1 += Fan5.voi_statistics[i*3+1]/(len(Fan5.voi_statistics)/3)
    avg_stat_5_comp2 += Fan5.voi_statistics[i*3+2]/(len(Fan5.voi_statistics)/3)
    avg_stat_6_vial += Fan6.voi_statistics[i*3]/(len(Fan6.voi_statistics)/3)
    avg_stat_6_comp1 += Fan6.voi_statistics[i*3+1]/(len(Fan6.voi_statistics)/3)
    avg_stat_6_comp2 += Fan6.voi_statistics[i*3+2]/(len(Fan6.voi_statistics)/3)
    avg_stat_7_vial += Fan7.voi_statistics[i*3]/(len(Fan7.voi_statistics)/3)
    avg_stat_7_comp1 += Fan7.voi_statistics[i*3+1]/(len(Fan7.voi_statistics)/3)
    avg_stat_7_comp2 += Fan7.voi_statistics[i*3+2]/(len(Fan7.voi_statistics)/3)
    avg_stat_8_vial += Fan8.voi_statistics[i*3]/(len(Fan8.voi_statistics)/3)
    avg_stat_8_comp1 += Fan8.voi_statistics[i*3+1]/(len(Fan8.voi_statistics)/3)
    avg_stat_8_comp2 += Fan8.voi_statistics[i*3+2]/(len(Fan8.voi_statistics)/3)

for i in range(int(len(Fan1.voi_statistics)/3)):
    std_stat_1_vial += (Fan1.voi_statistics[i*3]-avg_stat_1_vial)**2/(len(Fan1.voi_statistics)/3)
    std_stat_1_comp1 += (Fan1.voi_statistics[i*3+1]-avg_stat_1_comp1)**2/(len(Fan1.voi_statistics)/3)
    std_stat_1_comp2 += (Fan1.voi_statistics[i*3+2]-avg_stat_1_comp2)**2/(len(Fan1.voi_statistics)/3)
    std_stat_5_vial += (Fan5.voi_statistics[i*3]-avg_stat_5_vial)**2/(len(Fan5.voi_statistics)/3)
    std_stat_5_comp1 += (Fan5.voi_statistics[i*3+1]-avg_stat_5_comp1)**2/(len(Fan5.voi_statistics)/3)
    std_stat_5_comp2 += (Fan5.voi_statistics[i*3+2]-avg_stat_5_comp2)**2/(len(Fan5.voi_statistics)/3)
    std_stat_6_vial += (Fan6.voi_statistics[i*3]-avg_stat_6_vial)**2/(len(Fan6.voi_statistics)/3)
    std_stat_6_comp1 += (Fan6.voi_statistics[i*3+1]-avg_stat_6_comp1)**2/(len(Fan6.voi_statistics)/3)
    std_stat_6_comp2 += (Fan6.voi_statistics[i*3+2]-avg_stat_6_comp2)**2/(len(Fan6.voi_statistics)/3)
    std_stat_7_vial += (Fan7.voi_statistics[i*3]-avg_stat_7_vial)**2/(len(Fan7.voi_statistics)/3)
    std_stat_7_comp1 += (Fan7.voi_statistics[i*3+1]-avg_stat_7_comp1)**2/(len(Fan7.voi_statistics)/3)
    std_stat_7_comp2 += (Fan7.voi_statistics[i*3+2]-avg_stat_7_comp2)**2/(len(Fan7.voi_statistics)/3)
    std_stat_8_vial += (Fan8.voi_statistics[i*3]-avg_stat_8_vial)**2/(len(Fan8.voi_statistics)/3)
    std_stat_8_comp1 += (Fan8.voi_statistics[i*3+1]-avg_stat_8_comp1)**2/(len(Fan8.voi_statistics)/3)
    std_stat_8_comp2 += (Fan8.voi_statistics[i*3+2]-avg_stat_8_comp2)**2/(len(Fan8.voi_statistics)/3)

plt.figure(16)
#plt.plot(Fan1.time,avg_stat_1_vial/np.max(avg_stat_1_vial),label=Fan1.name)
plt.plot(Fan5.time,avg_stat_5_vial/np.max(avg_stat_5_vial),label=Fan5.name)
plt.plot(Fan6.time,avg_stat_6_vial/np.max(avg_stat_6_vial),label=Fan6.name)
plt.plot(Fan7.time,avg_stat_7_vial/np.max(avg_stat_7_vial),label=Fan7.name)
plt.plot(Fan8.time,avg_stat_8_vial/np.max(avg_stat_8_vial),label=Fan8.name)
plt.xlabel('Time');plt.ylabel('Activity');plt.title(f"Vial");plt.grid();plt.legend()

plt.figure(17)
#plt.plot(Fan1.time,avg_stat_1_comp1/np.max(avg_stat_1_vial),label=Fan1.name)
plt.plot(Fan5.time,avg_stat_5_comp1/np.max(avg_stat_5_vial),label=Fan5.name)
plt.plot(Fan6.time,avg_stat_6_comp1/np.max(avg_stat_6_vial),label=Fan6.name)
plt.plot(Fan7.time,avg_stat_7_comp1/np.max(avg_stat_7_vial),label=Fan7.name)
plt.plot(Fan8.time,avg_stat_8_comp1/np.max(avg_stat_8_vial),label=Fan8.name)
plt.xlabel('Time');plt.ylabel('Activity');plt.title(f"Comp1");plt.grid();plt.legend()

plt.figure(18)
#plt.plot(Fan1.time,avg_stat_1_comp2/np.max(avg_stat_1_vial),label=Fan1.name)
plt.plot(Fan5.time,avg_stat_5_comp2/np.max(avg_stat_5_vial),label=Fan5.name)
plt.plot(Fan6.time,avg_stat_6_comp2/np.max(avg_stat_6_vial),label=Fan6.name)
plt.plot(Fan7.time,avg_stat_7_comp2/np.max(avg_stat_7_vial),label=Fan7.name)
plt.plot(Fan8.time,avg_stat_8_comp2/np.max(avg_stat_8_vial),label=Fan8.name)
plt.xlabel('Time');plt.ylabel('Activity');plt.title(f"Comp2");plt.grid();plt.legend()

plt.figure(19)
#plt.plot(Fan1.time,std_stat_1_vial**(1/2),label=Fan1.name)
plt.plot(Fan5.time,std_stat_5_vial**(1/2),label=f"{Fan5.name} Statique")
plt.plot(Fan6.time,std_stat_6_vial**(1/2),label=f"{Fan6.name} Statique")
plt.plot(Fan7.time,std_stat_7_vial**(1/2),label=f"{Fan7.name} Dynamique")
plt.plot(Fan8.time,std_stat_8_vial**(1/2),label=f"{Fan8.name} Dynamique")
plt.xlabel('Time');plt.ylabel('Activity');plt.title(f"Vial Std");plt.grid();plt.legend()

plt.figure(20)
#plt.plot(Fan1.time,std_stat_1_comp1**(1/2),label=Fan1.name)
plt.plot(Fan5.time,std_stat_5_comp1**(1/2),label=f"{Fan5.name} Statique")
plt.plot(Fan6.time,std_stat_6_comp1**(1/2),label=f"{Fan6.name} Statique")
plt.plot(Fan7.time,std_stat_7_comp1**(1/2),label=f"{Fan7.name} Dynamique")
plt.plot(Fan8.time,std_stat_8_comp1**(1/2),label=f"{Fan8.name} Dynamique")
plt.xlabel('Time');plt.ylabel('Activity');plt.title(f"Comp1 Std");plt.grid();plt.legend()

plt.figure(21)
#plt.plot(Fan1.time,std_stat_1_comp2**(1/2),label=Fan1.name)
plt.plot(Fan5.time,std_stat_5_comp2**(1/2),label=f"{Fan5.name} Statique")
plt.plot(Fan6.time,std_stat_6_comp2**(1/2),label=f"{Fan6.name} Statique")
plt.plot(Fan7.time,std_stat_7_comp2**(1/2),label=f"{Fan7.name} Dynamique")
plt.plot(Fan8.time,std_stat_8_comp2**(1/2),label=f"{Fan8.name} Dynamique")
plt.xlabel('Time');plt.ylabel('Activity');plt.title(f"Comp2 Std");plt.grid();plt.legend()

print('Program ran until the end in ',"{:.2f}".format(time.time()-initial),' s')
plt.show()